apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: cnpg-system
    server: https://kubernetes.default.svc
  project: default
  sources:
  # - path: infra/cloudnativepg 
  #   repoURL: https://github.com/drewjprosser/argo-dev.git
  #   targetRevision: HEAD
  - repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.22.1
    chart: cloudnative-pg
    helm:
      releaseName: cloudnative-pg
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true