apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  # - repoURL: https://github.com/drewjprosser/argo-dev.git
  #   path: infra/openebs
  #   targetRevision: HEAD
  - repoURL: https://openebs.github.io/openebs
    targetRevision: 4.1.1
    chart: openebs
    helm:
      releaseName: openebs
      valuesObject:
        engines:
          local:
            lvm:
              enabled: false
            zfs:
              enabled: false
        mayastor:
          csi:
            node:
              initContainers:
                enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true