apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-3
parameters:
  fsType: xfs
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-1
parameters:
  fsType: xfs
  protocol: nvmf
  repl: "1"
provisioner: io.openebs.csi-mayastor