apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault-internal.int.prossertech.com"
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "prod-kubernetes"
          role: "prod-auth"
          serviceAccountRef:
            name: vault-auth
            namespace: external-secrets

          