apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: test-rec
spec:
  nodes: 3
  redisEnterpriseNodeResources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 1Gi
